
baseURL = "https://tileroyal.com/"
languageCode = "en-us"
title = "Tile Royal"
theme = "ananke"

enableRobotsTXT = true
buildFuture = false

[pagination]
pagerSize = 10

[params]
  mainSections = ["posts"]
